//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.EditoralOffice.MainOffce.Newslist {
    
    public partial class AllNewsTemplist {
        protected System.Web.UI.UpdatePanel panel;
        protected System.Web.UI.WebControls.DropDownList ddlChuyenmuc;
        protected System.Web.UI.HtmlControls.HtmlTable tblFilter;
        protected System.Web.UI.WebControls.TextBox txtCalendar;
        protected System.Web.UI.WebControls.TextBox txtToDate;
        protected System.Web.UI.WebControls.ImageButton btnFilter;
        protected System.Web.UI.WebControls.GridView grdListNews;
        protected System.Web.UI.HtmlControls.HtmlTable tblSearch;
        protected System.Web.UI.WebControls.TextBox txtKeyword;
        protected System.Web.UI.WebControls.Button btnSearch;
        protected System.Web.UI.WebControls.TextBox txtNguoiTao;
        protected System.Web.UI.WebControls.DropDownList cboCategory;
        protected System.Web.UI.WebControls.ObjectDataSource objListNewsSource;
    }
}
