//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.EditoralOffice.MainOffce.Newslist {
    
    public partial class ShowCommentReturn {
        protected System.Web.UI.WebControls.TextBox txtComment_Title;
        protected System.Web.UI.WebControls.TextBox txtComment_Content;
        protected System.Web.UI.WebControls.Button btnThoat;
    }
}
