//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.EditoralOffice.MainOffce.ListUserAction {
    
    public partial class ListAction {
        protected System.Web.UI.WebControls.GridView grdListNews;
        protected System.Web.UI.HtmlControls.HtmlTable tblSearch;
        protected System.Web.UI.WebControls.TextBox txtKeyword;
        protected System.Web.UI.WebControls.Button btnSearch;
        protected System.Web.UI.WebControls.ObjectDataSource objListNewsSource;
    }
}
