//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.Administrator.AdminPortal {
    
    public partial class AdminPortal {
        protected System.Web.UI.HtmlControls.HtmlTableRow Tr1;
        protected iiuga.Web.UI.TreeWeb tree;
        protected System.Web.UI.HtmlControls.HtmlGenericControl div1;
        protected System.Web.UI.WebControls.HyperLink lnkUsers;
        protected System.Web.UI.HtmlControls.HtmlGenericControl div3;
        protected System.Web.UI.WebControls.HyperLink lnkEditoral;
        protected System.Web.UI.HtmlControls.HtmlGenericControl div5;
        protected System.Web.UI.WebControls.HyperLink lnkChuyenMuc;
        protected System.Web.UI.HtmlControls.HtmlGenericControl diva;
        protected System.Web.UI.WebControls.HyperLink itemAccount;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divc;
        protected System.Web.UI.WebControls.LinkButton itemLogOut;
        protected Portal.GUI.EditoralOffice.MainOffce.OnLoad.onload Onload1;
        protected Portal.GUI.Administrator.AdminPortal.Tab TabCtrl;
        protected Portal.GUI.Administrator.AdminPortal.TabList TabListCtrl;
        protected Portal.GUI.Administrator.AdminPortal.Template TemplateCtrl;
        protected Portal.GUI.Administrator.AdminPortal.TemplateList TemplateListCtrl;
    }
}
