//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.Administrator.AdminPortal {
    
    public partial class Tab {
        protected Portal.API.Controls.Label Label3;
        protected Portal.API.Controls.LinkButton lnkSave;
        protected Portal.API.Controls.LinkButton lnkCancel;
        protected Portal.API.Controls.LinkButton lnkDelete;
        protected Portal.API.Controls.LinkButton lnkSaveTemplate;
        protected System.Web.UI.WebControls.Label lbError;
        protected System.Web.UI.WebControls.ValidationSummary validation;
        protected Portal.API.Controls.Label Label1;
        protected Portal.API.Controls.RequiredFieldValidator Requiredfieldvalidator1;
        protected System.Web.UI.WebControls.TextBox txtTitle;
        protected Portal.API.Controls.Label Label2;
        protected Portal.API.Controls.RequiredFieldValidator validator1;
        protected System.Web.UI.WebControls.TextBox txtReference;
        protected Portal.API.Controls.Label Label4;
        protected System.Web.UI.WebControls.DropDownList ddrSkins;
        protected Portal.API.Controls.Label Label5;
        protected System.Web.UI.WebControls.CheckBox chkIsHidden;
        protected Portal.API.Controls.Label Label6;
        protected System.Web.UI.WebControls.DropDownList ddrTemplateList;
        protected Portal.API.Controls.LinkButton lnkPreview;
    }
}
