//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.Administrator.AdminPortal {
    
    public partial class TabList {
        protected Portal.API.Controls.LinkButton lnkAddModule;
        protected System.Web.UI.WebControls.DataGrid Tabs;
    }
}
