//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.Administrator.AdminPortal {
    
    public partial class TemplateList {
        protected Portal.API.Controls.Label lblTemplateList;
        protected Portal.API.Controls.LinkButton lnkAddTemplate;
        protected Portal.API.Controls.LinkButton lnkFilterTemplateByType;
        protected System.Web.UI.WebControls.DropDownList ddrTemplateType;
        protected System.Web.UI.WebControls.DataGrid Templates;
    }
}
