//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.Administrator.AdminPortal {
    
    public partial class Template {
        protected Portal.API.Controls.Label Label3;
        protected Portal.API.Controls.LinkButton lnkSave;
        protected Portal.API.Controls.LinkButton lnkCancel;
        protected Portal.API.Controls.LinkButton lnkDelete;
        protected System.Web.UI.WebControls.Label lbError;
        protected System.Web.UI.WebControls.ValidationSummary validation;
        protected Portal.API.Controls.Label Label2;
        protected Portal.API.Controls.RequiredFieldValidator validator1;
        protected System.Web.UI.WebControls.TextBox txtReference;
        protected Portal.API.Controls.Label Label4;
        protected System.Web.UI.WebControls.DropDownList ddrTemplateType;
        protected Portal.GUI.Administrator.AdminPortal.ModuleEdit ModuleEditCtrl;
        protected Portal.GUI.Administrator.AdminPortal.ColumnEdit ColumnEditCtrl;
        protected Portal.GUI.Administrator.AdminPortal.ColumnList lstColumns;
        protected Portal.GUI.Administrator.AdminPortal.ModuleList lstModules;
    }
}
