//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFISYS.GUI.EditoralOffice.MainOffice.Menu {
    
    public partial class ProfileMenu {
        protected System.Web.UI.HtmlControls.HtmlGenericControl diva;
        protected System.Web.UI.WebControls.LinkButton itemAccount;
        protected System.Web.UI.HtmlControls.HtmlGenericControl div1;
        protected System.Web.UI.WebControls.HyperLink itemProfile;
        protected System.Web.UI.HtmlControls.HtmlGenericControl div2;
        protected System.Web.UI.WebControls.HyperLink itemQuanTriHeThong;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divb;
        protected System.Web.UI.WebControls.HyperLink itemHelp;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divc;
        protected System.Web.UI.WebControls.LinkButton itemLogOut;
    }
}
