//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.Administrator.GenerateTabs {
    
    public partial class CategoryEdit {
        protected System.Web.UI.WebControls.TextBox txtCategoryName;
        protected System.Web.UI.WebControls.TextBox txtCategoryDescription;
        protected System.Web.UI.WebControls.TextBox txtCategoryDisplayURL;
        protected System.Web.UI.WebControls.DropDownList cboCat;
        protected System.Web.UI.WebControls.DropDownList drEditionType;
        protected System.Web.UI.WebControls.FileUpload fldCategoryIcon;
        protected System.Web.UI.WebControls.CheckBox chkIsColumn;
        protected System.Web.UI.WebControls.CheckBox chkIsHidden;
        protected System.Web.UI.HtmlControls.HtmlInputHidden hdCatID;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.WebControls.Button btnUpdate;
        protected System.Web.UI.WebControls.Button btnCancel;
        protected System.Web.UI.WebControls.ObjectDataSource objCatSource;
    }
}
