//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.Administrator.GenerateTabs {
    
    public partial class GenerateTabs {
        protected System.Web.UI.WebControls.PlaceHolder plhEditionsList;
        protected System.Web.UI.WebControls.DataGrid dgrEditionTypes;
        protected Portal.API.Controls.Literal Literal1;
        protected System.Web.UI.WebControls.Literal ltrCurrentTemplateTabReference;
        protected Portal.API.Controls.LinkButton btnApplyTemplateToAllTab;
        protected Portal.API.Controls.LinkButton btnApplyTemplateToAllEditionTab;
        protected Portal.API.Controls.LinkButton btnApplyTemplateToAllParentCategoryTab;
        protected Portal.API.Controls.LinkButton btnApplyTemplateToAllSubCategoryTab;
        protected Portal.API.Controls.Literal Literal2;
        protected System.Web.UI.WebControls.DropDownList drdTabsList;
        protected Portal.API.Controls.LinkButton btnApplyTemplateToCustomTab;
    }
}
