//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.Administrator.GenerateTabs {
    
    public partial class MainModule {
        protected System.Web.UI.WebControls.PlaceHolder plcMenu;
        protected System.Web.UI.WebControls.PlaceHolder plcProfile;
        protected System.Web.UI.WebControls.PlaceHolder plcMain;
    }
}
