//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.Administrator.GenerateTabs {
    
    public partial class Menu {
        protected System.Web.UI.HtmlControls.HtmlGenericControl Div1;
        protected System.Web.UI.WebControls.HyperLink itemAddCat;
        protected System.Web.UI.HtmlControls.HtmlGenericControl Div2;
        protected System.Web.UI.WebControls.HyperLink itemListCat;
        protected System.Web.UI.HtmlControls.HtmlGenericControl Div3;
        protected System.Web.UI.WebControls.HyperLink itemComeAdmin;
        protected System.Web.UI.HtmlControls.HtmlGenericControl Div5;
        protected System.Web.UI.WebControls.HyperLink itemEditionType;
        protected System.Web.UI.HtmlControls.HtmlGenericControl Div4;
        protected System.Web.UI.WebControls.HyperLink itemComeOffice;
        protected System.Web.UI.HtmlControls.HtmlGenericControl Div6;
        protected System.Web.UI.WebControls.HyperLink itemHeThong;
    }
}
