//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.EditoralOffice.MainOffce.LogAction {
    
    public partial class LogAction {
        protected System.Web.UI.UpdatePanel UpdatePanel1;
        protected System.Web.UI.WebControls.GridView gvDataAction;
        protected System.Web.UI.WebControls.Label lblNumPageView;
        protected System.Web.UI.WebControls.DropDownList drPage;
        protected System.Web.UI.HtmlControls.HtmlTable tblSearch;
        protected System.Web.UI.WebControls.TextBox txtUserName;
        protected System.Web.UI.WebControls.Button txtFind;
        protected System.Web.UI.WebControls.TextBox txtHanhDong;
        protected System.Web.UI.WebControls.TextBox txtStartDate;
        protected System.Web.UI.WebControls.TextBox txtEndDate;
        protected System.Web.UI.WebControls.ObjectDataSource odsPage;
        protected System.Web.UI.WebControls.ObjectDataSource odsLogAction;
    }
}
