//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.EditoralOffice.MainOffce.editnews {
    
    public partial class blockedit {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected InnovaStudio.WYSIWYGEditor NewsContent;
        protected System.Web.UI.WebControls.Literal js;
        protected System.Web.UI.WebControls.Label arg1;
        protected System.Web.UI.WebControls.Label arg2;
    }
}
