//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.EditoralOffice.MainOffce.editnews {
    
    public partial class _default {
        protected System.Web.UI.WebControls.Literal ltrStyleSheet;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.ScriptManager ScriptManager1;
        protected InnovaStudio.WYSIWYGEditor NewsContent;
        protected System.Web.UI.WebControls.DropDownList Select2;
        protected System.Web.UI.WebControls.TextBox Text6;
        protected System.Web.UI.WebControls.TextBox Text7;
        protected System.Web.UI.WebControls.TextBox Text8;
        protected System.Web.UI.WebControls.TextBox Text9;
        protected System.Web.UI.WebControls.TextBox Text10;
        protected System.Web.UI.WebControls.DataList dtlListOfModules;
        protected System.Web.UI.WebControls.Label lblTitleNews;
        protected System.Web.UI.WebControls.Panel panel;
        protected System.Web.UI.WebControls.HiddenField customArg;
        protected System.Web.UI.WebControls.HiddenField customArg2;
        protected System.Web.UI.WebControls.HiddenField customViewstate;
        protected System.Web.UI.WebControls.LinkButton btnReload;
        protected System.Web.UI.WebControls.LinkButton LinkButton1;
        protected System.Web.UI.WebControls.Literal js;
    }
}
