//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.EditoralOffice.MainOffce.editnews {
    
    public partial class editModule {
        protected System.Web.UI.WebControls.Literal ltrStyleSheet;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlGenericControl container;
        protected System.Web.UI.WebControls.DropDownList Select2;
        protected System.Web.UI.WebControls.TextBox Text6;
        protected System.Web.UI.WebControls.TextBox Text7;
        protected System.Web.UI.WebControls.TextBox Text8;
        protected System.Web.UI.WebControls.TextBox Text9;
        protected System.Web.UI.WebControls.TextBox Text10;
        protected System.Web.UI.HtmlControls.HtmlGenericControl presentationContainer;
        protected System.Web.UI.WebControls.Label arg1;
        protected System.Web.UI.WebControls.Label arg2;
        protected System.Web.UI.WebControls.TextBox TextBox1;
        protected System.Web.UI.WebControls.Literal js;
    }
}
