//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.Administrator.CategoryManager {
    
    public partial class ProfileMenu {
        protected System.Web.UI.HtmlControls.HtmlGenericControl diva;
        protected System.Web.UI.WebControls.HyperLink itemAccount;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divb;
        protected System.Web.UI.WebControls.HyperLink itemHelp;
        protected System.Web.UI.HtmlControls.HtmlGenericControl divc;
        protected System.Web.UI.WebControls.LinkButton itemLogOut;
    }
}
