//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.Administrator.CategoryManager
{
    
    public partial class SetupLayout {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.ScriptManager ScriptManager1;
        protected System.Web.UI.WebControls.LinkButton btnSignmeout;
        protected System.Web.UI.WebControls.DropDownList cboModuleFolder;
        protected System.Web.UI.UpdatePanel UpdatePanel1;
        protected System.Web.UI.WebControls.DropDownList DropDownList2;
        protected System.Web.UI.WebControls.LinkButton LinkButton1;
        protected System.Web.UI.WebControls.HiddenField HiddenField1;
        protected System.Web.UI.HtmlControls.HtmlGenericControl workarea;
        protected System.Web.UI.UpdatePanel upEditModuleForm;
        protected System.Web.UI.WebControls.Label lblModuleType;
        protected System.Web.UI.WebControls.TextBox txtTitle;
        protected System.Web.UI.WebControls.TextBox txtReference;
        protected System.Web.UI.WebControls.TextBox txtCacheTime;
        protected System.Web.UI.WebControls.Repeater rptRuntimeProperties;
        protected System.Web.UI.WebControls.Button btnBindModuleEditForm;
        protected System.Web.UI.WebControls.Button btnSaveModule;
    }
}
