//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFISYS.GUI.Front_End.bacth_test8 {
    
    public partial class _default {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Literal ltrNewsTitle;
        protected System.Web.UI.WebControls.Image imgNewsAvatar;
        protected System.Web.UI.WebControls.Literal ltrImageNote;
        protected System.Web.UI.WebControls.Literal ltrNewsInit;
        protected System.Web.UI.WebControls.Literal ltrNewsDetail;
    }
}
