//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.EditoralOffice.MainOffce.Draft {
    
    public partial class preview {
        protected System.Web.UI.WebControls.Literal ltrTitle;
        protected System.Web.UI.WebControls.Literal ltrImage;
        protected System.Web.UI.WebControls.Literal ltrSapo;
        protected System.Web.UI.WebControls.Literal ltrContent;
    }
}
