//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.EditoralOffice.MainOffce.NewsThread {
    
    public partial class Threaddetails {
        protected System.Web.UI.WebControls.Label lblThreadTitle;
        protected System.Web.UI.WebControls.GridView grdThreadDetails;
        protected System.Web.UI.WebControls.DropDownList cboPage;
        protected System.Web.UI.WebControls.Literal Literal0;
        protected System.Web.UI.WebControls.LinkButton lnkAddNews;
        protected System.Web.UI.WebControls.LinkButton lnkRealDel;
        protected System.Web.UI.WebControls.TextBox txtKeyword;
        protected System.Web.UI.WebControls.Button btnSearch;
        protected System.Web.UI.WebControls.DropDownList cboThread;
        protected System.Web.UI.WebControls.ObjectDataSource objdspage;
        protected System.Web.UI.WebControls.ObjectDataSource objThreadSource;
        protected System.Web.UI.WebControls.ObjectDataSource objThreaddetailSource;
    }
}
