//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.EditoralOffice.MainOffce.NewsThread {
    
    public partial class ThreadList {
        protected System.Web.UI.WebControls.Label lblLabel;
        protected System.Web.UI.WebControls.GridView gvData;
        protected System.Web.UI.WebControls.LinkButton lbThemMoi;
    }
}
