//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFISYS.GUI.EditoralOffice.MainOffce.OnLoad.UserControl {
    
    public partial class SumNews {
        protected System.Web.UI.WebControls.HyperLink hplPublished;
        protected System.Web.UI.WebControls.Literal ltrSumNewsPublished;
        protected System.Web.UI.WebControls.HyperLink hplNewsWaitingApprove;
        protected System.Web.UI.WebControls.Literal ltrSumNewsWaitingApprove;
        protected System.Web.UI.WebControls.HyperLink hplNewsWaitingEdit;
        protected System.Web.UI.WebControls.Literal ltrSumNewsWaitingEdit;
    }
}
