//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal {
    
    public partial class ListThread {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected Portal.GUI.EditoralOffice.MainOffce.NewsThread.ListThread ListThread1;
    }
}
